# name: Actionsflow
# on:
#   # schedule:
#   #   - cron: "0 * * * *"
#   push:
#     branches:
#       - master
#   repository_dispatch:
#   workflow_dispatch:
#     inputs:
#       include:
#         description: "--include: workflow file filter, you can use glob format to filter your workflows, the default value is empty value, means no filter will be using"
#         required: false
#         default: ""
#       force:
#         description: "--force: whether force to run workflow, true or false"
#         required: false
#         default: "false"
#       verbose:
#         description: "--verbose: debug workflow, true or false"
#         required: false
#         default: "false"
# jobs:
#   run:
#     runs-on: ubuntu-latest
#     name: Run
#     concurrency: actionsflow
#     steps:
#       - uses: actions/checkout@v3
#       - name: Run Actionsflow
#         uses: actionsflow/actionsflow-action@v1.3.0
#         with:
#           args: "build --include ${{ github.event.inputs.include || ''}} -f ${{github.event.inputs.force=='true' && 'true' || 'false'}} --verbose ${{github.event.inputs.verbose=='true' && 'true' || 'false'}}"
#           json-secrets: ${{ toJSON(secrets) }}
#           json-github: ${{ toJSON(github) }}
#       - name: Setup act
#         uses: actionsflow/setup-act-for-actionsflow@v1.2.0
#       - name: Run act
#         run: act --workflows ./dist/workflows --secret-file ./dist/.secrets --eventpath ./dist/event.json --env-file ./dist/.env -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest

name: Actionsflow
on:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master
  repository_dispatch:
  workflow_dispatch:
    inputs:
      include:
        description: "--include: workflow file filter, you can use glob format to filter your workflows, the default value is empty value, means no filter will be using"
        required: false
        default: ""
      force:
        description: "--force: whether force to run workflow, true or false"
        required: false
        default: "false"
      verbose:
        description: "--verbose: debug workflow, true or false"
        required: false
        default: "false"

jobs:
  run:
    runs-on: ubuntu-latest
    name: Run
    concurrency: actionsflow
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Actionsflow
        run: npm install -g actionsflow

      - name: Run Actionsflow
        run: |
          actionsflow build \
            --include "${{ github.event.inputs.include || '' }}" \
            -f "${{ github.event.inputs.force == 'true' && 'true' || 'false' }}" \
            --verbose "${{ github.event.inputs.verbose == 'true' && 'true' || 'false' }}"

      - name: Setup act
        uses: actionsflow/setup-act-for-actionsflow@v1.2.0

      - name: Run act
        run: act --workflows ./dist/workflows --secret-file ./dist/.secrets --eventpath ./dist/event.json --env-file ./dist/.env -P ubuntu-latest=ghcr.io/catthehacker/ubuntu:act-latest

      - name: Commit and Push README changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Determine the default branch (master or main)
          DEFAULT_BRANCH=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
          echo "Default branch: $DEFAULT_BRANCH"
          
          # Check if there are any changes to commit
          if ! git diff --quiet HEAD -- README.md || ! git diff --cached --quiet HEAD -- README.md; then
            echo "Changes detected in README.md"
            
            # Clean up any previous stash
            git stash clear || true
            
            # Create a backup of our changes
            cp README.md README.md.backup
            
            # Fetch the latest state
            git fetch origin $DEFAULT_BRANCH
            
            # Reset to the latest remote state
            git reset --hard origin/$DEFAULT_BRANCH
            
            # Restore our changes
            cp README.md.backup README.md
            rm README.md.backup
            
            # Check if there are still changes after sync
            if ! git diff --quiet HEAD -- README.md; then
              git add README.md
              git commit -m "Update README with daily fact"
              
              # Retry push with exponential backoff
              for attempt in {1..5}; do
                echo "Push attempt $attempt..."
                if git push origin $DEFAULT_BRANCH; then
                  echo "✅ Successfully pushed changes"
                  exit 0
                else
                  echo "❌ Push failed, attempt $attempt of 5"
                  if [ $attempt -lt 5 ]; then
                    # Wait before retry (exponential backoff)
                    sleep_time=$((2**attempt))
                    echo "Waiting ${sleep_time} seconds before retry..."
                    sleep $sleep_time
                    
                    # Fetch latest and reset
                    git fetch origin $DEFAULT_BRANCH
                    git reset --hard origin/$DEFAULT_BRANCH
                    
                    # Restore our changes again
                    cp README.md.backup README.md 2>/dev/null || echo "Backup not found, using current changes"
                    
                    if ! git diff --quiet HEAD -- README.md; then
                      git add README.md
                      git commit -m "Update README with daily fact" || true
                    fi
                  else
                    echo "❌ Failed to push after 5 attempts"
                    exit 1
                  fi
                fi
              done
            else
              echo "No changes remain after sync"
            fi
          else
            echo "No changes detected in README.md"
          fi
